### ISSUE TITLE
adding new images?

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/helics-buildenv#2]
What is the process for adding a new image so it builds and uploads to dockerhub?  

I want to try a few different things with the sanitizers image.  I don't think the current sanitizers image is working quite right for thread sanitizer so I want to try a few different ones and probably make an image for a couple different versions of LLVM.

**Comment by nightlark** [comment]
Can you check the sanitizer image again after [this workflow run](https://github.com/GMLC-TDC/helics-buildenv/commit/c47d5fb2ba6959b46182bd3dc089e37b9d033af5/checks?check_suite_id=349316414) finishes? I fixed an issue a few days ago with the scripts not being right (html surrounding the downloaded script), and I think I need to update the rebuild trigger to handle when non-documentation files change in a subfolder.

Adding a new image is just creating a folder with a Dockerfile. You have a syntax error in your Dockerfile: https://github.com/GMLC-TDC/helics-buildenv/commit/ce9acfd0196e64400d15bac7aae3ff5dec08c640/checks?check_suite_id=349258066

Adding support to build multiple configurations is a bit of a pain, do you think there's enough difference between LLVM sanitizer versions (any difference observed when running an older version of tsan locally)? I would kind of hope newer versions aren't getting worse at detecting issues.

The current CI builder matrix image has a special setup to handle multiple versions of compilers and boost. The Dockerfile needs to take an argument when building to alter the version. https://github.com/GMLC-TDC/helics-buildenv/blob/master/.github/workflows/docker-image-update.yml needs to add the path to the Dockerfile with multiple configurations as an ignore path, and then a workflow with a matrix strategy set similar to https://github.com/GMLC-TDC/helics-buildenv/blob/master/.github/workflows/ci-docker-images.yml needs to be added.

Do you anticipate wanting to have multiple configs for a lot of different docker images? If so, instead add a docker-build.sh file to the subfolder with a series of `docker build` and `docker push` commands for each build configuration. It will have a trade off in build time, but then I can make the Dockerfile rebuilding not require creating a custom workflow for each multiple configuration case. I should probably make that change to the ci-builder image too so that it doesn't have a custom set up for it's workflow.

**Comment by phlptp** [comment]
The main issue I am trying to figure out is there seems to be a big difference in the results from clang-8 thread sanitizer to clang 9.    With  clang-9 tsan we get a large number of "double lock of mutex"  warnings.  And in most cases I haven't been able to figure out the mechanics of that, the output is not that helpful in most cases, which effectively renders the sanitizer useless.    So for the moment we need to run the thread santizer on clang-8,  while the others seem to work fine on clang-9 in the sanitizers.  

There are a few potential issues that are causing it.  One is that there is actually a new issue that clang-9 picks up that we just haven't figured out how to resolve yet.  

the second is a bug in clang-9 for false positive detection

the third is that there is a mismatch in the libc++ library that is causing some issues in tsan.    So what I wanted to do was create a new image that just matched the llvm libc++ and libc++abi to the version, to see if that resolved the issue or not.  

Failing that I would like a sanitizers-8 image which uses clang-8 instead of 9 for all the sanitizers in the buildenv repo,  then we can drop the old tsan image.    

So the santizers_test folder would likely replace the sanitizers folder once we verify it is working equivalently since it would fix the target instead of using the llvm trunk which is a moving target.  and We would likely create a new folder for sanitizers-8 to replace the helics/clang-tsan image which is in its own repo right now and make a consistent set using clang-8.  

I suppose someday we may want a different image using the gcc version of the sanitizers which may find different things, but that is later on.
